### ISSUE TITLE
warning: use of deprecated variant `clap::AppSettings::TrailingVarArg`

### ISSUE THREAD

**Issue by ghost** [andybug/notify-complete#2]
Hi, I noticed this was added to the [AUR](https://aur.archlinux.org/packages/notify-complete) and I wanted to try it out. During makepkg operation it threw the below `warning`, which I thought might be helpful to report here:

```
warning: use of deprecated variant `clap::AppSettings::TrailingVarArg`: Replaced with `Command::trailing_var_arg` and `Command::is_trailing_var_arg_set`
   --> src/config.rs:468:78
    |
468 |     #[clap(author, version, about, long_about = None, setting = AppSettings::TrailingVarArg)]
    |                                                                              ^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

The package was built and seems to work as expected.

**Comment by andybug** [comment]
Thanks for the report @glitsj16! `clap-rs` just [updated](https://github.com/clap-rs/clap/releases/tag/v3.1.0) yesterday and deprecated it, I'm looking at fixing it now.
